create table "public"."availability_filter_combos" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "care_unit" text not null,
    "facility" text not null,
    "emergency_care" boolean not null,
    "availability_unit" text not null,
    "isolation_type" text
);


alter table "public"."availability_filter_combos" enable row level security;

CREATE UNIQUE INDEX availability_filter_combos_pkey ON public.availability_filter_combos USING btree (id);

alter table "public"."availability_filter_combos" add constraint "availability_filter_combos_pkey" PRIMARY KEY using index "availability_filter_combos_pkey";

grant delete on table "public"."availability_filter_combos" to "anon";

grant insert on table "public"."availability_filter_combos" to "anon";

grant references on table "public"."availability_filter_combos" to "anon";

grant select on table "public"."availability_filter_combos" to "anon";

grant trigger on table "public"."availability_filter_combos" to "anon";

grant truncate on table "public"."availability_filter_combos" to "anon";

grant update on table "public"."availability_filter_combos" to "anon";

grant delete on table "public"."availability_filter_combos" to "authenticated";

grant insert on table "public"."availability_filter_combos" to "authenticated";

grant references on table "public"."availability_filter_combos" to "authenticated";

grant select on table "public"."availability_filter_combos" to "authenticated";

grant trigger on table "public"."availability_filter_combos" to "authenticated";

grant truncate on table "public"."availability_filter_combos" to "authenticated";

grant update on table "public"."availability_filter_combos" to "authenticated";

grant delete on table "public"."availability_filter_combos" to "service_role";

grant insert on table "public"."availability_filter_combos" to "service_role";

grant references on table "public"."availability_filter_combos" to "service_role";

grant select on table "public"."availability_filter_combos" to "service_role";

grant trigger on table "public"."availability_filter_combos" to "service_role";

grant truncate on table "public"."availability_filter_combos" to "service_role";

grant update on table "public"."availability_filter_combos" to "service_role";


